### ISSUE TITLE
Add screenshot of a PC-9821 running Windows 95

### ISSUE THREAD

**Issue by evv42** [NCommander/progress-pride-win16#4]
OS: Windows 95 Japanese
Hardware: PC-9821 Ne3
![pc9821](https://user-images.githubusercontent.com/39388347/204109424-d1d3ce88-5ef5-41e6-8812-eb306b5ce14b.png)

**Comment by evv42** [comment]
Goofed up

**Comment by NCommander** [comment]
Saw this was made a PR, merged it!
